<?php
namespace App\Os;

use App\Vps;

/**
* radvd (Router Advertisement Daemon) Service Management Class
*
* WHY THIS EXISTS: DHCPv6 has no default-route option -- RFC 8415 never defined
* one. A guest can only learn its default router from a Router Advertisement, so
* "DHCPv6 only, no RA" is not buildable. On top of that, a client only bothers
* speaking DHCPv6 at all when an RA sets the Managed flag.
*
* Upstream switches typically advertise the on-link /64 with M=0 / O=0 / A=1,
* which tells every guest "don't use DHCPv6, invent your own address in here."
* That is why VPSes come up with random SLAAC addresses that our dhcpd6 never
* assigned, and it makes abuse attribution impossible.
*
* This class generates an radvd.conf that says the opposite -- M=1, O=1, A=0 --
* so the host's dhcpd6 becomes the only source of guest addressing.
*
* IMPORTANT: this config alone is not enough. br0 bridges the uplink to every
* vnetN, so the switch's RA still reaches the guests, and a guest honours EVERY
* RA it receives rather than picking a winner. The upstream RA must also be
* filtered off the guest ports -- see ra-filter.sh in the vps_host_server repo.
*/
class Radvd
{
	/**
	* is the service running (only reports true if both the binary exists and a process is running)
	* @return bool
	*/
	public static function isRunning() {
		Vps::getLogger()->write(Vps::runCommand('command -v radvd >/dev/null 2>&1', $return));
		if ($return != 0) {
			Vps::getLogger()->error('radvd binary not found in PATH');
			return false;
		}
		Vps::getLogger()->write(Vps::runCommand('pidof radvd >/dev/null', $return));
		return $return == 0;
	}

	/**
	* returns the name of the radvd config file
	* @return string
	*/
	public static function getConfFile() {
		return '/etc/radvd.conf';
	}

	/**
	* returns the name of the radvd service
	* @return string
	*/
	public static function getService() {
		return 'radvd';
	}

	/**
	* Works out which interface carries a given IPv6 network, so the generated
	* config targets the real bridge rather than assuming br0. Falls back to br0
	* (and then to the first bridge present) when the route lookup comes up empty.
	* @param string $network the network in CIDR form, e.g. 2604:a00:50:4::/64
	* @return string interface name
	*/
	public static function detectInterface($network) {
		$out = Vps::runCommand('ip -6 route show '.escapeshellarg($network).' 2>/dev/null');
		if (preg_match('/\bdev\s+(\S+)/', (string)$out, $m))
			return $m[1];
		if (file_exists('/sys/class/net/br0'))
			return 'br0';
		$bridges = glob('/sys/class/net/*/bridge');
		if (is_array($bridges) && count($bridges) > 0)
			return basename(dirname($bridges[0]));
		return 'br0';
	}

	/**
	* regenerates the radvd.conf file
	* @param bool $display defaults to false, true to display file contents instead of write them
	* @return bool indicates success
	*/
	public static function rebuildConf($display = false) {
		$host = Vps::getHostInfo();
		if (!is_array($host) || !isset($host['vlans6'])) {
			Vps::getLogger()->error('There appears to have been a problem with the host info, perhaps try again?');
			return false;
		}
		if (!is_array($host['vlans6']) || count($host['vlans6']) == 0) {
			Vps::getLogger()->info('Host has no IPv6 vlans; skipping radvd.conf');
			return true;
		}
		// Group networks by the interface that carries them: radvd wants one
		// interface block containing all of that link's prefixes, not one block
		// per prefix. Duplicate interface stanzas make radvd refuse to start.
		$byInterface = [];
		foreach ($host['vlans6'] as $vlanId => $vlanData) {
			if (!isset($vlanData['vlans6_networks']) || trim((string)$vlanData['vlans6_networks']) === '')
				continue;
			$network = trim($vlanData['vlans6_networks']);
			if (!preg_match('#^[0-9A-Fa-f:]+/\d{1,3}$#', $network)) {
				Vps::getLogger()->error("Skipping malformed IPv6 network '{$network}' for vlan {$vlanId}");
				continue;
			}
			$interface = self::detectInterface($network);
			if (!isset($byInterface[$interface]))
				$byInterface[$interface] = [];
			$byInterface[$interface][] = $network;
		}
		if (count($byInterface) == 0) {
			Vps::getLogger()->error('No usable IPv6 networks found; not writing '.self::getConfFile());
			return false;
		}
		$file = '# Generated by provirted -- do not edit by hand, changes will be overwritten.'.PHP_EOL
			.'# Regenerate with: provirted rebuild-dhcp conf'.PHP_EOL
			.'#'.PHP_EOL
			.'# AdvManagedFlag on     (M=1) -> guests take their ADDRESS from our dhcpd6'.PHP_EOL
			.'# AdvOtherConfigFlag on (O=1) -> guests take DNS/etc from our dhcpd6'.PHP_EOL
			.'# AdvAutonomous off     (A=0) -> guests must NOT SLAAC themselves an address'.PHP_EOL
			.'#'.PHP_EOL
			.'# The upstream switch advertises the same prefix with A=1. Its RA must be'.PHP_EOL
			.'# filtered off the guest ports (ra-filter.sh) or it will re-enable SLAAC'.PHP_EOL
			.'# regardless of what this file says.'.PHP_EOL.PHP_EOL;
		foreach ($byInterface as $interface => $networks) {
			$file .= 'interface '.$interface.PHP_EOL
				.'{'.PHP_EOL
				.'	AdvSendAdvert on;'.PHP_EOL
				.'	MinRtrAdvInterval 30;'.PHP_EOL
				.'	MaxRtrAdvInterval 100;'.PHP_EOL
				.'	AdvManagedFlag on;'.PHP_EOL
				.'	AdvOtherConfigFlag on;'.PHP_EOL
				.'	AdvLinkMTU 1500;'.PHP_EOL
				// Once the upstream RA is filtered off the guest ports, this host is
				// the only thing left telling guests where the default route is, so it
				// has to advertise itself as a router. It already forwards and holds a
				// static default of its own, so it can carry that traffic.
				.'	AdvDefaultLifetime 1800;'.PHP_EOL
				.'	AdvDefaultPreference high;'.PHP_EOL.PHP_EOL;
			foreach ($networks as $network) {
				$file .= '	prefix '.$network.PHP_EOL
					.'	{'.PHP_EOL
					.'		AdvOnLink on;'.PHP_EOL
					.'		AdvAutonomous off;'.PHP_EOL
					.'		AdvRouterAddr on;'.PHP_EOL
					.'		AdvValidLifetime 2592000;'.PHP_EOL
					.'		AdvPreferredLifetime 604800;'.PHP_EOL
					.'	};'.PHP_EOL.PHP_EOL;
			}
			$file .= '	RDNSS 2606:4700:4700::1111 2001:4860:4860::8888'.PHP_EOL
				.'	{'.PHP_EOL
				.'		AdvRDNSSLifetime 1800;'.PHP_EOL
				.'	};'.PHP_EOL
				.'};'.PHP_EOL.PHP_EOL;
		}
		if ($display === false) {
			if (@file_put_contents(self::getConfFile(), $file) === false) {
				Vps::getLogger()->error('Could not write '.self::getConfFile().' (check permissions)');
				return false;
			}
			self::restart();
		} else {
			Vps::getLogger()->write('cat > '.self::getConfFile().' <<EOF'.PHP_EOL.$file.'EOF'.PHP_EOL);
		}
		return true;
	}

	/**
	* restarts the service
	* @return bool indicates success
	*/
	public static function restart() {
		$service = self::getService();
		$svcArg = escapeshellarg($service);
		$svcEsc = escapeshellcmd($service);
		Vps::getLogger()->write(Vps::runCommand("systemctl restart {$svcArg} 2>/dev/null || service {$svcArg} restart 2>/dev/null || /etc/init.d/{$svcEsc} restart 2>/dev/null", $return));
		if ($return != 0) {
			Vps::getLogger()->error("Could not restart {$service} (exit {$return}); router advertisements may still reflect the old config");
			return false;
		}
		return true;
	}
}
